{
  "uid" : "b957b8b45c457b29",
  "name" : "test_divide",
  "fullName" : "tests.test_calculator.TestCalculator#test_divide",
  "historyId" : "9356db49794aba22ea9dff5a609de199",
  "time" : {
    "start" : 1640107158414,
    "stop" : 1640107158415,
    "duration" : 1
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL this test is expecting failure\n\nAssertionError: assert 2.9999999999999996 == 3.0\n +  where 2.9999999999999996 = <function Calculator.divide at 0x7f9767d14820>(0.3, 0.1)\n +    where <function Calculator.divide at 0x7f9767d14820> = Calculator.divide",
  "statusTrace" : "self = <tests.test_calculator.TestCalculator object at 0x7f9768175930>\n\n    @pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_divide(self):\n>       assert Calculator.divide(0.3, 0.1) == 3.0\nE       assert 2.9999999999999996 == 3.0\nE        +  where 2.9999999999999996 = <function Calculator.divide at 0x7f9767d14820>(0.3, 0.1)\nE        +    where <function Calculator.divide at 0x7f9767d14820> = Calculator.divide\n\ntests/test_calculator.py:28: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "xunit_setup_class_fixture_TestCalculator",
    "time" : {
      "start" : 1640107158375,
      "stop" : 1640107158375,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0,
    "attachmentsCount" : 0
  } ],
  "afterStages" : [ {
    "name" : "xunit_setup_class_fixture_TestCalculator::0",
    "time" : {
      "start" : 1640107158442,
      "stop" : 1640107158442,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function TestCalculator.<lambda> at 0x7f9767d14ca0>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_calculator"
  }, {
    "name" : "subSuite",
    "value" : "TestCalculator"
  }, {
    "name" : "host",
    "value" : "fv-az210-783"
  }, {
    "name" : "thread",
    "value" : "2717-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_calculator"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(condition=<function TestCalculator.<lambda> at 0x7f9767d14ca0>, reason='this test is expecting failure')" ]
  },
  "source" : "b957b8b45c457b29.json",
  "parameterValues" : [ ]
}